.\"Layout note:
.\" This document uses .RS and .RE a lot as well as a general abuse of .SS.
.\" Refer to man(7) for their definitions.  There wasn't a clear way to make
.\" the output readable without hacking with indentations.  This
.\" human-readable code isn't.  A layout redesign may be in order.
.TH ARCHIVE 1 "2017\-05\-28" "Source Mage GNU/Linux" "System Administration"
.SH NAME
archive \- work with archive and compressed files
.SH SYNOPSIS
.B alter
.RI [ option ]
.SH "DESCRIPTION"
archive is part of the
.SM sorcery
source\-code package management suite. It is a command\-line tool to
work with archive files.
.SH "COMMANDS"

.SH "NOTES"


.SH "WARNING"


.SH "AUTHOR"


.SH "REPORTING BUGS"

.SH "SEE ALSO"
.BR alter(8),
.BR cast (8),
.BR cleanse (8),
.BR confmeld (8),
.BR dispel (8),
.BR gaze (1),
.BR grimoire (5),
.BR scribbler (8),
.BR scribe (8),
.BR sorcery (8),
.BR sorcery_config (8),
.BR summon (8)
.SH "WARRANTY"
This is free software with ABSOLUTELY NO WARRANTY
